apiVersion: v1
kind: Service
metadata:
  name: baseline
  labels:
    app.kubernetes.io/component: baseline-round-robin
spec:
  selector:
    llm-d.ai/guide: precise-prefix-cache-routing
    llm-d.ai/role: decode
  ports:
  - name: http
    port: 8000
    targetPort: modelserver
    protocol: TCP
